### ISSUE TITLE
Node not recognized

### ISSUE THREAD

**Issue by gaoxuxu110** [theUpsider/ComfyUI-Logic#12]
**Describe the bug**
Node not recognized

**To Reproduce**
[Math_Test.json](https://github.com/user-attachments/files/16061477/Math_Test.json)

**Expected behavior**
All nodes related to "comfyui_logic" cannot be displayed in the workflow in recent updates

**Screenshots**
![Snipaste_2024-07-02_11-56-35](https://github.com/theUpsider/ComfyUI-Logic/assets/52225349/3aae219a-4b5e-488b-ae3b-83499326d1ca)

**Version:**
 - when update "refactor:Update node class mappings and display names"

**Additional context**

**Comment by theUpsider** [comment]
I changed the display names for global uniqueness. This requires manually adding the nodes again.

Unfortunately my names were not unique before which led to the package being incompatible with other nodes. This should be a one time thing. I'm sorry for the trouble.

**Comment by theUpsider** [comment]
I changed the display names for global uniqueness. This requires manually adding them again.

Unfortunately my names were not unique before which led to the package being incompatible with other nodes. This should be a one time thing.
