### ISSUE TITLE
Cannot load the node

### ISSUE THREAD

**Issue by mikebilly** [theUpsider/ComfyUI-Logic#14]
Fresh factory reset, cannot load the Comfy-Logic node.
ComfyUI-Manager (V2.48.5) and Comfy-Org_ComfyUI_frontend/1.2.9
ComfyUI Revision: 2464 Released on '2024-08-04'
![image](https://github.com/user-attachments/assets/189810e0-2113-47d5-b3e2-176b878b1035)
![image](https://github.com/user-attachments/assets/3a8a6e63-8d20-4c7b-a4af-05b3c62a247a)

**Comment by theUpsider** [comment]
See the other issues on the repository. I changed the names. So you have to add the nodes again. They got renamed for naming collision reasons.

**Comment by mikebilly** [comment]
![image](https://github.com/user-attachments/assets/97fa4f94-2bee-425d-ae5c-58e48ff59565)
@theUpsider I don't see the other nodes, like Compare and If.
Also freshly reinstalled:
![image](https://github.com/user-attachments/assets/5de2eedc-a8ea-41b7-8ce5-b994b6fe514a)
This issue only happened yesterday when I updated ComfyUI and ComfyUI-Manager to latest versions.

**Comment by theUpsider** [comment]
Thanks for letting me know! Will check
