### ISSUE TITLE
Unable to load node: in ANY return A else B

### ISSUE THREAD

**Issue by patrice74** [theUpsider/ComfyUI-Logic#15]
Impossible to load the node: in ANY return A else B with the new ComfyUI FrontEnd

No errors on the server, the custom node loads well.

ComfyUI: 2489[8115d8](2024-08-07)
Manager: V2.46.3

The other nodes seem ok

Remedy :

Modify the line RETURN_NAMES = "?" of the "class IfExecute:" by: RETURN_NAMES = ("?",)

**Comment by theUpsider** [comment]
Thanks for the issue! I changed the lines and will make a commit.
