### ISSUE TITLE
lost node after upadate comfyui

### ISSUE THREAD

**Issue by K-O-N-B** [theUpsider/ComfyUI-Logic#18]
it show:
![image](https://github.com/user-attachments/assets/b711e81f-00c0-4182-8f28-217047e1718e)
![image](https://github.com/user-attachments/assets/4c61323c-738b-4242-8004-93336a4147fb)

but I have install it
![image](https://github.com/user-attachments/assets/3ccf8a06-4005-4332-b36b-3b3c240a76c7)

and not find in missing node
![image](https://github.com/user-attachments/assets/b3dcc90a-4cf9-4989-843a-8ee4e168e306)

**Comment by theUpsider** [comment]
Did you try adding it again?

**Comment by jerrydavos** [comment]
Hey @K-O-N-B , the "If any" node you are using is from this [Comfy eden Pipeline](https://github.com/edenartlab/eden_comfy_pipelines) which has some dependency error after recent update, check your console logs, the pipeline node is failing to load with some error.
  
Can you please post full console log of the errors if possible here. 

There are 2 nodes with the same name one is from Comfy eden Pipeline and other from Comfy Logic
![image](https://github.com/user-attachments/assets/9d5ba2b7-1797-43b4-a456-6937a577fdd9)

Solution: 

1) Delete the eden pipeline folder from custom nodes and re-install the comfy eden pipeline manually and pip install the requirements manually

If the above don't work then

2) Disable the Comfy-Pipline nodes from the manager and replace with the **original** logic "If any" node. 

This one: 
![image](https://github.com/user-attachments/assets/251b65fe-4847-40ad-b684-42e9a1fe2e10)


Hope it helps

**Comment by theUpsider** [comment]
I updated the repo so the most recent comfy logic node is the correct one. Just replace the node in your work flow with the new version 👍

**Comment by K-O-N-B** [comment]
> Hey @K-O-N-B , the "If any" node you are using is from this [Comfy eden Pipeline](https://github.com/edenartlab/eden_comfy_pipelines) which has some dependency error after recent update, check your console logs, the pipeline node is failing to load with some error.
> 
> Can you please post full console log of the errors if possible here.
> 
> There are 2 nodes with the same name one is from Comfy eden Pipeline and other from Comfy Logic ![image](https://private-user-images.githubusercontent.com/152957217/358890579-9d5ba2b7-1797-43b4-a456-6937a577fdd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjEyNDEsIm5iZiI6MTcyNDA2MDk0MSwicGF0aCI6Ii8xNTI5NTcyMTcvMzU4ODkwNTc5LTlkNWJhMmI3LTE3OTctNDNiNC1hNDU2LTY5MzdhNTc3ZmRkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwOTQ5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGMyYzFhNzdiMTk5MWE5NGE2ODk5MTZmNTQwMTM0YzZhZmQ1NzhlYmMyMGU1M2NhMmM3NjA0ZTU4NWE4NDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nIApxs-WDYM3or-B6hokUU7pAeRoN81zeWueN1C2da8)
> 
> Solution:
> 
> 1. Delete the eden pipeline folder from custom nodes and re-install the comfy eden pipeline manually and pip install the requirements manually
> 
> If the above don't work then
> 
> 2. Disable the Comfy-Pipline nodes from the manager and replace with the **original** logic "If any" node.
> 
> This one: ![image](https://private-user-images.githubusercontent.com/152957217/358890630-251b65fe-4847-40ad-b684-42e9a1fe2e10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjEyNDEsIm5iZiI6MTcyNDA2MDk0MSwicGF0aCI6Ii8xNTI5NTcyMTcvMzU4ODkwNjMwLTI1MWI2NWZlLTQ4NDctNDBhZC1iNjg0LTQyZTlhMWZlMmUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwOTQ5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjEzZTNjOTk4ZTJhZTVlNjQ5OTkyM2UxZjc1NjhlZWM0ZGRjYzNhYjZjYTRiZjk5ODAxYTQ1M2UyNTUxMmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FokQbePPSlls1cOCBeNYPfRPugMc3bPa4fNj4uUQgDk)
> 
> Hope it helps

this is helpful, thank you!
