### ISSUE TITLE
object of type 'int' has no len()

### ISSUE THREAD

**Issue by alexbofa** [theUpsider/ComfyUI-Logic#2]
Hello, I have problem. I tried using this [workflow](https://civitai.com/models/128556?modelVersionId=146728) 1.09/1.08/1.0. The same error is everywhere

Console
```bat
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\ComfyUI\execution.py", line 96, in get_output_data
    output_is_list = [False] * len(results[0])
TypeError: object of type 'int' has no len()
```
![Screen-1913](https://github.com/theUpsider/ComfyUI-Logic/assets/58225118/3feae244-d0f1-4611-b10c-bba7eb8abc28)

**Comment by theUpsider** [comment]
@alexbofa Can you send me your workflow so I can reproduce the error?

**Comment by alexbofa** [comment]
@theUpsider Hello, this workflow from [civitai](https://civitai.com/models/128556?modelVersionId=146728)
[comfyuiInpaintWorkflow_v109.zip](https://github.com/theUpsider/ComfyUI-Logic/files/12691199/comfyuiInpaintWorkflow_v109.zip)
