### ISSUE TITLE
Can you add stop button like if false then stop it makes ultimate automation I make a workflow for output selection but stop node required 

### ISSUE THREAD

**Issue by Abhay13332** [theUpsider/ComfyUI-Logic#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by theUpsider** [comment]
Would be cool. Probably needs some imports from the original scripts or the manager..

**Comment by Abhay13332** [comment]
Use it ,it has ultimate automation possibility I try almost all nodes related to it but they have issue so try to make it

**Comment by theUpsider** [comment]
Duplicate https://github.com/theUpsider/ComfyUI-Logic/issues/7
