### ISSUE TITLE
IF_FALSE should not be mandatory

### ISSUE THREAD

**Issue by BenDes21** [theUpsider/ComfyUI-Logic#7]
Hi, for the IF node, how can I return " nothing " or just stop the node if the condition IF_False is trigger ? My goal is to save an image if_true is valid or dont save if_false is trigger. Thanks

**Comment by theUpsider** [comment]
Hey there. You can open a pull request if you feel confident in your programming skills. Otherwise, I dont know when I will find time to implement this change, yet.

**Comment by theUpsider** [comment]
I tried to implement. Doesnt work the way we want to. ComfyUI just doesnt offer this possibility.

**Comment by theUpsider** [comment]
Closing for now. If anyone wants to attempt, please welcome.
