### ISSUE TITLE
Make String node input multiline

### ISSUE THREAD

**Issue by DaniDipp** [theUpsider/ComfyUI-Logic#8]
**Is your feature request related to a problem? Please describe.**
I would like to use the String node for my prompts without it being cut off.

**Describe the solution you'd like**
The String input field should be multiline, similar to the inbuilt Primitive node.

**Describe alternatives you've considered**
Implementing it myself. Happy to do a PR though.

**Additional context**
![pPJ7c 1](https://github.com/theUpsider/ComfyUI-Logic/assets/17002453/62a23d64-c633-415a-84ac-a52921cddd62)

**Comment by theUpsider** [comment]
@DaniDipp I would really appreciate a PR from you!
